version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: fixitflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - fixitflow-network

  redis:
    image: redis:7-alpine
    container_name: fixitflow-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fixitflow-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fixitflow-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/fixitflow?authSource=admin
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - fixitflow-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: fixitflow-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fixitflow-network

volumes:
  mongodb_data:

networks:
  fixitflow-network:
    driver: bridge
